version: '2'

services:
  solar_forecast:
    image: gridappsd/solar-forecast-app
    build: https://github.com/NREL/Solar-Forecasting.git
    ports:
      - 9002:9002
    environment:
      GRIDAPPSD_URI: tcp://gridappsd:61613
